#!/usr/bin/env bash
# configuration web-01 to have an HTTP response header

#updating packages
sudo apt-get update
sudo apt-get install -y nginx 

echo "Hello World! | sudo tee /var/www/html/index.html

# perfoming a redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/@billgates/videos

# Creating a custom error page

echo " The page is not found" | sudo tee /var/www/html/404.html

#custom HTTP response header

sudo sed -i "service_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#Tets for syntax errors
sudo nginx -t 

#restart nginx 
sudo service nginx restart 
