#!/bin/env/bash 
# Configure ufw against all incoming traaffic
# exppert 22, 80, 443

sudo ufw deny default incoming
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
